# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_measurements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple_measurements.proto',
  package='carla_ros_bridge',
  syntax='proto2',
  serialized_pb=_b('\n\x19simple_measurements.proto\x12\x10\x63\x61rla_ros_bridge\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"6\n\nRotation3D\x12\r\n\x05pitch\x18\x01 \x01(\x02\x12\x0b\n\x03yaw\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\"\x8d\x02\n\x12SimpleMeasurements\x12,\n\x08location\x18\x01 \x01(\x0b\x32\x1a.carla_ros_bridge.Vector3D\x12,\n\x08rotation\x18\x02 \x01(\x0b\x32\x1a.carla_ros_bridge.Vector3D\x12\x34\n\x10\x61ngular_velocity\x18\x03 \x01(\x0b\x32\x1a.carla_ros_bridge.Vector3D\x12\x33\n\x0flinear_velocity\x18\x04 \x01(\x0b\x32\x1a.carla_ros_bridge.Vector3D\x12\x30\n\x0c\x61\x63\x63\x65leration\x18\x05 \x01(\x0b\x32\x1a.carla_ros_bridge.Vector3D')
)




_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='carla_ros_bridge.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='carla_ros_bridge.Vector3D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='carla_ros_bridge.Vector3D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='carla_ros_bridge.Vector3D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=90,
)


_ROTATION3D = _descriptor.Descriptor(
  name='Rotation3D',
  full_name='carla_ros_bridge.Rotation3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='carla_ros_bridge.Rotation3D.pitch', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='carla_ros_bridge.Rotation3D.yaw', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='carla_ros_bridge.Rotation3D.roll', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=146,
)


_SIMPLEMEASUREMENTS = _descriptor.Descriptor(
  name='SimpleMeasurements',
  full_name='carla_ros_bridge.SimpleMeasurements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='carla_ros_bridge.SimpleMeasurements.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='carla_ros_bridge.SimpleMeasurements.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='carla_ros_bridge.SimpleMeasurements.angular_velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='carla_ros_bridge.SimpleMeasurements.linear_velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='carla_ros_bridge.SimpleMeasurements.acceleration', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=418,
)

_SIMPLEMEASUREMENTS.fields_by_name['location'].message_type = _VECTOR3D
_SIMPLEMEASUREMENTS.fields_by_name['rotation'].message_type = _VECTOR3D
_SIMPLEMEASUREMENTS.fields_by_name['angular_velocity'].message_type = _VECTOR3D
_SIMPLEMEASUREMENTS.fields_by_name['linear_velocity'].message_type = _VECTOR3D
_SIMPLEMEASUREMENTS.fields_by_name['acceleration'].message_type = _VECTOR3D
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Rotation3D'] = _ROTATION3D
DESCRIPTOR.message_types_by_name['SimpleMeasurements'] = _SIMPLEMEASUREMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'simple_measurements_pb2'
  # @@protoc_insertion_point(class_scope:carla_ros_bridge.Vector3D)
  ))
_sym_db.RegisterMessage(Vector3D)

Rotation3D = _reflection.GeneratedProtocolMessageType('Rotation3D', (_message.Message,), dict(
  DESCRIPTOR = _ROTATION3D,
  __module__ = 'simple_measurements_pb2'
  # @@protoc_insertion_point(class_scope:carla_ros_bridge.Rotation3D)
  ))
_sym_db.RegisterMessage(Rotation3D)

SimpleMeasurements = _reflection.GeneratedProtocolMessageType('SimpleMeasurements', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEMEASUREMENTS,
  __module__ = 'simple_measurements_pb2'
  # @@protoc_insertion_point(class_scope:carla_ros_bridge.SimpleMeasurements)
  ))
_sym_db.RegisterMessage(SimpleMeasurements)


# @@protoc_insertion_point(module_scope)
